title: Angelica Pan
description: Technical Writer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://angelica-pan.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Angelica Pan
  image: '/assets/img/profile.png'
  job: Technical Writer
  bio: Technical Writer at <a href="https://wandb.ai/site" target="_blank">Weights & Biases</a>
  email: angelica.s.pan@gmail.com

# Contact links
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#   - name: Facebook
#     link: https://facebook.com/
#   - name: Instagram
#     link: https://instagram.com/


# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
# google-analytics: # add your identifier. For example UA-99631805-1.

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging
  
# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# portfolio collection
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/
    order:
      - pcibex.md
      - handout.md
      - quickstart.md
      - practical.md


# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
